### ISSUE TITLE
mp3 export error

### ISSUE THREAD

**Issue by asdbimbaj** [bgbennyboy/DoubleFine-Explorer#1]
i used the program to extract mp3 from brutal legends file ,but in every language voice pack file witch is the ***-streaming.fsb. the files are listed ,and i can see the size, but when i want to hear the sample there's an error message "Error playing stream! Error code:5". i just extracted some of them ,but they were broken.

**Comment by bgbennyboy** [comment]
Just checked and you're right. This worked in the last version so its a regression. I'll look into it now. Thanks for the bug report!

**Comment by bgbennyboy** [comment]
From the MP3 specs "For Layer II there are some combinations of bitrate and mode which are not allowed" - in those streaming FSB's they use a combination which isn't supposed to be allowed but plays just fine (bitrate 80, channelmode 0). Fixed in latest commit.

**Comment by asdbimbaj** [comment]
Thank you! one more question. I am begginer in this ,but how can i use it (compile from source) or edit the software?

**Comment by bgbennyboy** [comment]
I'll do a new binary release shortly. To compile it you need a version of Delphi (I use XE6 but I think 2010 or later will work). You'll also need a number of components:
Virtual treeview
Jedi Code Library
Jedi Visual Code Library
Graphics32
AdvGlowButton
ZLibEx
Vampyre Imaging Library

**Comment by bgbennyboy** [comment]
New version released now.
