### ISSUE TITLE
Folder Structure for Psychonauts (Steam)

### ISSUE THREAD

**Issue by wattostudios** [bgbennyboy/DoubleFine-Explorer#4]
Hi there,

I found your software when trying to determine the Folder Structure used in the Psychonauts (Steam) PKG file, but it looks like you've had some of the same difficulties as me, trying to work out just how the folder names are stored.

After a bit of trial and error, I think I've jagged the structure as this...

`// FOLDER DIRECTORY`
`  // for each letter (12 bytes per entry)`
`    2 - Letter (Unicode)`
`    2 - Return Pos 1`
`    2 - Return Pos 2`
`    2 - Letter ID (incremental from 1)`
`    2 - First File ID in this Folder`
`    2 - Last File ID in this Folder`

... which doesn't really explain much, but the code below (from my program) will probably give you a better idea...

`      // Process the Folders Directory`
`      fm.seek(foldersOffset);`

`      String[] pathNames = new String[1000];`
`      int[][] pathIDs = new int[1000][2];`
`      int numPaths = 0;`

`      String[] returnNames = new String[100];`
`      int[] returnIDs = new int[100];`
`      int numReturns = 0;`

`      String currentName = "";`

`      for (int i = 0; i < numFolders; i++) {`
`        // 1 - Letter`
`        char nextLetter = (char) fm.readByte();`

`        // 1 - null`
`        fm.skip(1);`

`        // 2 - Return Pos 1`
`        int returnPos1 = fm.readShort();`
`        if (returnPos1 != 0) {`
`          returnNames[numReturns] = currentName;`
`          returnIDs[numReturns] = returnPos1;`
`          numReturns++;`
`        }`

`        // 2 - Return Pos 2`
`        int returnPos2 = fm.readShort();`
`        if (returnPos2 != 0) {`
`          returnNames[numReturns] = currentName;`
`          returnIDs[numReturns] = returnPos2;`
`          numReturns++;`
`        }`

`        currentName += nextLetter; // needs to be done AFTER the return pos`

`        // 2 - Character ID (incremental from 1)`
`        fm.skip(2);`

`        // 2 - First File ID in this Folder`
`        int startIndex = fm.readShort();`

`        // 2 - Last File ID in this Folder`
`        int endIndex = fm.readShort();`

`        if (startIndex != 0 && endIndex != 0) {`
`          pathNames[numPaths] = currentName;`
`          pathIDs[numPaths] = new int[] { startIndex, endIndex };`
`          numPaths++;`
`          //System.out.println("Directory " + currentName + " for files " + startIndex + "-" + endIndex);`
`        }`

`        // process the returns now`
`        int thisID = i + 1;`
`        for (int r = 0; r < numReturns; r++) {`
`          if (returnIDs[r] == thisID) {`
`            // found one`
`            currentName = returnNames[r];`

`            // shuffle the names array to remove this entry`
`            if (r != numReturns - 1) {`
`              returnIDs[r] = returnIDs[numReturns - 1];`
`              returnNames[r] = returnNames[numReturns - 1];`
`            }`

`            numReturns--;`
`          }`
`        }`
`      }`

The general idea is that Return Pos 1 and 2 are both just indications of returning to this particular point in the string. Once you've processed the entry with that ID, discard all the characters back to this point, and start building the string forward again.

The code above just reads in all the letters 1 at a time. If either of the Return Pos 1 or 2 are filled, it stores the currentName in an array, so it's easy to return back to. At the end of each loop iteration, we check all the return positions - if we find one that matches, we roll the currentName back to the previous value stored in the array.

The end result from this loop is that you'll have an array pathNames with all the path names in it, and an array pathIDs with the start and end File IDs corresponding to that path, so you just have to go through and prepend the paths to the files.

Sorry for not editing your code directly, but hopefully this info is enough if you want to try adjusting your program.

watto

[code.txt](https://github.com/bgbennyboy/DoubleFine-Explorer/files/5062989/code.txt)

**Comment by bgbennyboy** [comment]
Cheers! The directory structure has been a mystery for a long time
