### ISSUE TITLE
Support new ppak format.

### ISSUE THREAD

**Issue by JohnPeel** [bgbennyboy/DoubleFine-Explorer#5]
I haven't completed the documentation yet, but I've reverse engineered the new ppf format and wrote a library for it.

You can view it at https://github.com/JohnPeel/repkg/blob/main/ppf/src/lib.rs

**Comment by bgbennyboy** [comment]
Nicely done! Looking at it now

**Comment by JohnPeel** [comment]
If it helps, this is how I'm regenerating the dds headers. The only thing I can't do is generate a single dds file for a game_texture that has animation_info.

https://github.com/JohnPeel/repkg/blob/main/repkg/src/main.rs#L75
https://github.com/JohnPeel/repkg/blob/main/dds/src/lib.rs

**Comment by JohnPeel** [comment]
Ah, also going to note, this is for Psychonauts, I haven't looked at the other games.

**Comment by JohnPeel** [comment]
Though at least in Psychonauts, these are in cpp files under a CommonLibs folder, so it's probably the same code in other games.

**Comment by bgbennyboy** [comment]
Psychonauts is the only one that uses these I think. All the other games used simpler formats for their archives (thankfully)

**Comment by bgbennyboy** [comment]
Its challenging as I've never used Rust before, but I'm having a go at understanding it. 
Thanks for this, its great that you've RE'ed the new format.

**Comment by JohnPeel** [comment]
> Its challenging as I've never used Rust before, but I'm having a go at understanding it.
> Thanks for this, its great that you've RE'ed the new format.

I'll try to finish writing up the documentation. It'll probably be easier to read than the source.

**Comment by JohnPeel** [comment]
https://github.com/JohnPeel/repkg/wiki/PPF-File-Format

**Comment by JohnPeel** [comment]
So far, the only unknown things inside the format are the `unknown0` in AnimationInfo and Texture.

**Comment by JohnPeel** [comment]
`Texture.texture`'s size can be calculated using normal DDS methods.

If the `format` is `DXT1`, `DXT3`, or `DXT5`, you multiply width, height, and block size (8 for `DXT1`, 16 for others) for each mipmap level.
Else, you multiply width, height, and bytes per pixel (this comes from each format name, `R5G6B5` -> (5 + 6 + 5) / 8 = 2) for each mipmap level.

**Comment by bgbennyboy** [comment]
Fantastic! Thank you.

**Comment by JohnPeel** [comment]
I've fleshed out a few more parts, we're down to only 2 unknown (and these unknown are not needed to extract textures as DDS files).

The first is right before a palette. The other is in GameTexture.

**Comment by JohnPeel** [comment]
Just noting I've moved the ppf package to a subdirectory in https://github.com/JohnPeel/repkg.

I went and updated all the links in this issue.

We're also down to 1 last unknown in GameTexture.

**Comment by bgbennyboy** [comment]
Nice one. I've been adding the code to DoubleFine Explorer. I just got distracted by Psychonauts 2 being released :)

**Comment by JohnPeel** [comment]
Any update on this?

**Comment by bgbennyboy** [comment]
I started implementing it and then got busy. I have a backlog of stuff to update and release. The plan is to finish it over the christmas holidays.

**Comment by bgbennyboy** [comment]
I've added support for the new PPF bundles. I'll do a new release later. Many, many thanks for your excellent work on this.
