### ISSUE TITLE
Kinect Party Pack Files

### ISSUE THREAD

**Issue by ChaoticPumpkin** [bgbennyboy/DoubleFine-Explorer#7]
Hi there, 

I've been trying to extract the file packages inside of Double Fine's Kinect Party, and I thought this might be the best place to ask for help. The files I've been looking at specifically are in `<Xbox Package>/360/Packs`. In this folder there are a bunch of `.~p` and their corresponding `.~h` files. (See attached files).

From looking at some of the source code of Double Fine Explorer, I presume the `.~h` files are metadata, etc. for the `.~p` files under the same name. The program is able to open some of the files despite it not recognizing `compression type 12`, and even export some data, but only about half of the exported text files seem correct, as you can see from these two exported lua files from `Man_Script.~h`. Images and other assets don't seem to export or load at all.
![Screenshot_20231024_161807](https://github.com/bgbennyboy/DoubleFine-Explorer/assets/59938482/00e05cd4-e1ae-4bb8-8076-895878d74be2)

I'm going to continue experimenting with this, but I would be very grateful if you would take a look at them. [Packs.zip - 247MiB](https://drive.google.com/file/d/1dSnM5FSbbZfrHxm75adMsVJu3RIOGB_V/view?usp=sharing)

**Comment by bgbennyboy** [comment]
I've had a quick look, the format doesn't look any different to the other games. Some files are decoded correctly because they aren't compressed. In other games using these resources file compression is done with zlib - but not here. 
As its an xbox 360 game my guess is that the compression is XMemCompress. I haven't got time to do any more today but I'll look into it more when I get chance and possibly add support for it to DoubleFine Explorer.

**Comment by bgbennyboy** [comment]
Had a quick look, compression type 12 is indeed XMemCompress
[debug.lua.txt](https://github.com/bgbennyboy/DoubleFine-Explorer/files/13182023/debug.lua.txt)

**Comment by ChaoticPumpkin** [comment]
Awesome! And thanks for figuring that out, I haven't really done much modding on Xbox games before, and must have missed anything about XMemCompress in my research lol.

**Comment by ChaoticPumpkin** [comment]
I had some more time to look at this, how did you extract the data from XMemCompress? I've looked at a few different tools and code samples, but I haven't managed to recreate the extracted file you attached.

**Comment by bgbennyboy** [comment]
I used a dll from the old xbox sdk. I've added support for it to Doublefine Explorer now, I'll upload a new release when I get time.
